# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation.

# General Config
DEFAULT_BRANCH: main
FILEIO_REPORTER: false
IGNORE_GITIGNORED_FILES: true
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: false

# JavaScript/TypeScript Config
JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .js
  - .jsx
TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .ts
  - .tsx
# Workaround to also run prettier on other supported file types
JSON_PRETTIER_FILE_EXTENSIONS:
  - .json
  - .css
  - .scss
  - .htm
  - .html
  - .md

# Black Config
PYTHON_BLACK_ARGUMENTS:
  - "--preview"

# Linters
ENABLE_LINTERS:
  # Languages
  - JAVA_CHECKSTYLE
  - JAVA_PMD
  - JAVASCRIPT_ES
  - JAVASCRIPT_PRETTIER
  - JSX_ESLINT
  - KOTLIN_KTLINT
  - MAKEFILE_CHECKMAKE
  - PYTHON_BLACK
  - PYTHON_MYPY
  - PYTHON_RUFF
  - RUST_CLIPPY
  - SQL_SQL_LINT
  - SQL_SQLFLUFF
  - TSX_ESLINT
  - TYPESCRIPT_ES
  - TYPESCRIPT_PRETTIER

  # Formats
  - CSS_STYLELINT
  - ENV_DOTENV_LINTER
  - GRAPHQL_GRAPHQL_SCHEMA_LINTER
  - HTML_DJLINT
  - HTML_HTMLHINT
  - JSON_JSONLINT
  - JSON_ESLINT_PLUGIN_JSONC
  - JSON_V8R
  - JSON_PRETTIER
  - JSON_NPM_PACKAGE_JSON_LINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - XML_XMLLINT
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - YAML_V8R

  # Tooling
  - ACTION_ACTIONLINT
  - DOCKERFILE_HADOLINT

  # Other
  - REPOSITORY_GIT_DIFF
