name: Publish Poetry Project to PyPI (reusable)

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory to use'
        required: true
        type: string
      python-version:
        description: 'Python version to use'
        required: true
        type: string
    secrets:
      PYPI_TOKEN:
        description: 'PyPI token'
        required: true
      GITHUB_PAT:
        description: 'GitHub Personal Access Token'
        required: false

jobs:
  build:
    uses: lars-reimann/.github/.github/workflows/poetry-codecov-reusable.yml@main
    with:
      working-directory: ${{ inputs.working-directory }}
      python-version: ${{ inputs.python-version }}
      coverage: false

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'poetry'

      - name: Use Node.js 20.x
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install NPM dependencies
        run: npm ci

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT || secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
