name: Publish Poetry Project to PyPI (reusable)

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory to use'
        required: true
        type: string
      python-version:
        description: 'Python version to use'
        required: true
        type: string
    secrets:
      PYPI_TOKEN:
        description: 'PyPI token'
        required: true
      GITHUB_PAT:
        description: 'GitHub Personal Access Token'
        required: false

jobs:
  build:
    uses: lars-reimann/.github/.github/workflows/poetry-codecov-reusable.yml@main
    with:
      working-directory: ${{ inputs.working-directory }}
      python-version: ${{ inputs.python-version }}
      coverage: false

  release:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.3
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - uses: bjoluc/semantic-release-config-poetry@v2.2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          github_token: ${{ secrets.GITHUB_PAT || secrets.GITHUB_TOKEN }}
