name: Check Pull Request Format (Reusable)

on: 
  workflow_call:

concurrency:
  group: ${{ github.head_ref }}-pr-format-reusable
  cancel-in-progress: true

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
