name: Check Pull Request Format (Reusable)

on:
  workflow_call:

jobs:
  check-title:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    concurrency:
      group: ${{ github.head_ref }}__pr-format-reusable__check-title
      cancel-in-progress: true

    steps:
      - uses: amannn/action-semantic-pull-request@v4.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
